name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup
        run: pip install pytest ruff

      - name: Lint
        run: ruff check .

      - name: Test
        run: pytest
